name: itsmylive
description: Flutter Live Rtmp and Srt.
version: 2.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  camera: ^0.10.6
  battery_plus: ^6.2.0
  path_provider: ^2.1.5
  flutter_plugin_android_lifecycle: 2.0.27 # via varsion
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5 # via varsion
  shared_preferences: ^2.5.2
  flutter_lints: ^4.0.0
  audio_session: ^0.1.25
  permission_handler: ^11.3.1
  network_info_plus: ^6.1.3
  package_info_plus: ^8.2.0 # License
  mylive_libraly:
    path: ../mylive_libraly

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
  assets:
    - lib/assets/appicon.png
    - lib/assets/sample.png

