name: itsmylive
description: Flutter rtmp.
version: 0.9.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  camera: ^0.10.5+3
  intl: ^0.17.0
  battery_plus: ^2.1.0
  path_provider: ^2.0.8
  flutter_native_splash: ^1.3.1
  hooks_riverpod: ^2.0.2
  shared_preferences: ^2.0.13
  flutter_lints: ^2.0.0

  native_device_orientation: ^1.1.4
  audio_session: any
  permission_handler: ^9.0.2
  #haishin_kit: ^0.11.0

  apivideo_live_stream: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/sample.png

